### ISSUE TITLE
Empty Json Body

### ISSUE THREAD

**Issue by kelvindu** [isfaaghyth/IAK-Advanced#1]
Mas untuk menghandle json yang kosong di RxOkhttp kayak gimana ya? error yang saya hadapi sama dengan yang di bahas di sini : https://github.com/square/retrofit/issues/1554, tapi di situ solusinya adalah menggunakan rxjava2 dan retrofit2.

request json yang saya hadapi kurang lebih seperti ini:
{
  "data" : "",
  "id": 1
}
saya tidak perlu menyimpan "data" tetapi karena nilainya yg kosong membuat saya tidak bisa mengconvert satu json tsbt menjadi gson.

Thank you

**Comment by isfaaghyth** [comment]
bisa diterapkan AdapterFactory ini:
http://chrisjenx.com/gson-empty-json-to-null/

**Comment by isfaaghyth** [comment]
kasusnya seperti ini:
{
"data" : "",
"id": 1
}
atau ini:
{
"data" : null,
"id": 1
}
??

**Comment by kelvindu** [comment]
yg pertama mas, tapi sudah resolved hehe. saya berhasil implemen ke retrofit jadinya. tapi skrg jadi ada isu baru mas.

jadi recyclerview nya mencoba nge bind datanya sebelum masuk, makanya jadi ga ke tampil apa".
saya kepikiran mau di caching tapi masih experimen sih pake yg mana yg mudah hehehe

**Comment by kelvindu** [comment]
udh resolved mas, saya close ya hehe

**Comment by isfaaghyth** [comment]
wah, ok.
maaf, baru ada kabar lagi.
macbook ku kemarin ngga bisa nyala hehe.
sipsip
